os:
  - linux
  - windows

addons:
  chrome: stable

language: node_js

node_js:
  - "10"
  - "8"
  - "6"

matrix:
  fast_finish: true
  allow_failures:
    - os: windows

cache:
  directories:
    - node_modules
